### ISSUE TITLE
DOI not converted

### ISSUE THREAD

**Issue by alexanderzatko** [rvnproject/ravenDOI#9]
On https://www.researchgate.net/publication/226971106_Who_Benefits_from_Complexity_A_View_from_Futuna page, the DOI link pointing to http://dx.doi.org/10.1007/978-1-4419-6300-0_5 is not converting to sci-hub link. On other pages I have used the extension, it worked fine. Thanks for the effort.

**Comment by mde-pach** [comment]
@alexanderzatko  What is your version of RavenDOI and your current browser ?

**Comment by alexanderzatko** [comment]
tested with FF and xtension version 1.0.3

**Comment by mde-pach** [comment]
The bug is fix in the 1.0.4 (currently in master) by #10 
It was due to a regex change from me.
(this project really need test obviously)

Thank you for your contributing !
